abbr n 'nnn -C '
abbr please 'sudo '
abbr pls 'sudo '
abbr q 'exit'
abbr :q 'exit'
abbr ls 'ls --color -1 --group-directories-first '
abbr ll 'ls -vAFlh'
abbr la 'ls -1A'
abbr lt 'tree -L 2'
abbr c 'clear'
abbr h 'history'
abbr tree 'tree --dirsfirst -F -L 3'
abbr mkdir 'mkdir -p -v'
abbr v 'nvim'
abbr vi 'nvim'
abbr vim 'nvim'
abbr grep 'grep --color=auto'
abbr df 'df -h'
abbr du 'du -h'
abbr fetch 'fastfetch'
abbr less 'less -r'
abbr o 'xdg-open'
abbr dnf 'sudo dnf'
abbr ds 'dnf search'
abbr sdu 'sudo dnf update'
abbr sdi 'sudo dnf install'
abbr sdr 'sudo dnf remove'
abbr fu 'flatpak update'
abbr update 'sudo dnf update && flatpak update'
abbr ytx 'yt-dlp -x --audio-format mp3 --audio-quality best'
abbr fvim 'fzf | xargs nvim'
abbr nnn 'nnn -C'

# shortcuts
abbr esp 'cd ~/Documents/Tuks/2023/ESP411/'
abbr epr 'cd ~/Documents/Tuks/2023/EPR400/'
abbr eprc 'cd ~/Documents/Tuks/2023/EPR400/code/cpp'
abbr rust 'cd ~/Documents/Rust'
abbr sites 'cd ~/Documents/Web/Sites/'

# my programs
abbr socc 'bash ~/Documents/Rust/scaling_and_offset_circuit_calculator/target/release/circuit_calculator'
abbr bela 'sudo sshfs -o allow_other root@192.168.7.2:/root/Bela/ /mnt/bela && cd /mnt/bela'
abbr mount_bela 'sudo sshfs -o allow_other root@192.168.7.2:/ /mnt/bela'
abbr ssh_bela 'sudo ssh 192.168.7.2 -l root'
